name: Submit IndexNow Request To Bing

on:
  push:
    branches: ["main"]  # 根据需要替换为你的主分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  indexnow:
    name: IndexNow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 可以根据需要调整 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 安装 requests 库

      - name: Run IndexNow script
        run: |
          python index_now.py  # 替换为你的 Python 脚本文件名